### ISSUE TITLE
RxJs plugins are AMD modules. Shim config need to be removed

### ISSUE THREAD

**Issue by ivanobulo** [webjars/rxjs#9]
I found the following in the RequireJS site regarding shim configuration and I have actually have some weird issues with it.

>Remember: only use shim config for non-AMD scripts,
>scripts that do not already call define(). The shim
>config will not work correctly if used on AMD scripts,
>in particular, the exports and init config will not
>be triggered, and the deps config will be confusing
>for those cases.

I'll remove shim config and I also have to change "rxjs" to "rx" because RxJS plugins have a reference to "rx".

**Comment by jamesward** [comment]
Looks like this was all fixed in #10.
